// $ANTLR 2.7.6 (2005-12-22): "gramatica.g" -> "TheParser.java"$

public interface TheParserTokenTypes {
	int EOF = 1;
	int NULL_TREE_LOOKAHEAD = 3;
	int LITERAL_programa = 4;
	int LITERAL_fimprog = 5;
	int LITERAL_declare = 6;
	int LITERAL_inteiro = 7;
	int LITERAL_decimal = 8;
	int LITERAL_booleano = 9;
	int T_Id = 10;
	int T_virg = 11;
	int T_pontof = 12;
	int LITERAL_leia = 13;
	int T_ap = 14;
	int T_fp = 15;
	int LITERAL_escreva = 16;
	int T_texto = 17;
	int T_attr = 18;
	int LITERAL_se = 19;
	int LITERAL_entao = 20;
	int LITERAL_es = 21;
	int T_soma = 22;
	int T_subt = 23;
	int T_mult = 24;
	int T_divi = 25;
	int T_num = 26;
	int T_menor = 27;
	int T_maior = 28;
	int T_maiorI = 29;
	int T_menorI = 30;
	int T_igualI = 31;
	int T_difeI = 32;
	int T_comm_i = 33;
	int T_comm_f = 34;
	int T_igual = 35;
	int T_excla = 36;
	int T_e = 37;
	int T_ou = 38;
	int T_blank = 39;
}
