// $ANTLR 2.7.6 (2005-12-22): "gramatica.g" -> "TheParser.java"$

public interface TheParserTokenTypes {
	int EOF = 1;
	int NULL_TREE_LOOKAHEAD = 3;
	int LITERAL_programa = 4;
	int LITERAL_fimprog = 5;
	int LITERAL_declare = 6;
	int LITERAL_inteiro = 7;
	int LITERAL_decimal = 8;
	int LITERAL_booleano = 9;
	int T_Id = 10;
	int T_virg = 11;
	int T_pontof = 12;
	int LITERAL_leia = 13;
	int T_ap = 14;
	int T_fp = 15;
	int LITERAL_escreva = 16;
	int T_texto = 17;
	int T_attr = 18;
	int T_num = 19;
	int LITERAL_verdade = 20;
	int LITERAL_mentira = 21;
	int LITERAL_se = 22;
	int LITERAL_entao = 23;
	int LITERAL_ss = 24;
	int LITERAL_senao = 25;
	int LITERAL_es = 26;
	int T_igualI = 27;
	int T_difeI = 28;
	int T_soma = 29;
	int T_subt = 30;
	int T_mult = 31;
	int T_divi = 32;
	int T_comm_i = 33;
	int T_comm_f = 34;
	int T_menor = 35;
	int T_maior = 36;
	int T_menorI = 37;
	int T_maiorI = 38;
	int T_igual = 39;
	int T_excla = 40;
	int T_e = 41;
	int T_ou = 42;
	int T_blank = 43;
}
